# 商城
admin_v2_marketing_mall:
  name: 商城
  parent: admin_v2
  before: admin_v2_education
  router_name: admin_v2_marketing_mall
  visible: (is_show_mall()) #没接入教育云和无网情况下不显示营销商城
  children:
    admin_v2_basic_content_resource_group2:
      name: 商城
      router_name: admin_v2_marketing_mall
      is_group: true
      children:
        admin_v2_purchase_market_menu1:
          name: 商城
          router_name: admin_v2_marketing_mall
          children:
            admin_v2_purchase_market_tab1:
              name: 商城
              router_name: admin_v2_marketing_mall
              disable: true
