services:
  api_token_header_listener:
    class: MarketingMallBundle\Security\Firewall\MallAuthTokenAuthenticationListener
    arguments:
      - '@service_container'

  marketing_mall_user_event_subscriber:
    class: MarketingMallBundle\Event\UserEventSubscriber
    arguments: [ '@biz' ]
    tags:
      - { name: codeages_plugin.event.subscriber }
